const actionTags = {
    ADD_BOARD: "ADD_BOARD",
    UPDATE_BOARD: "UPDATE_BOARD",
    DELETE_BOARD: "DELETE_BOARD",
    RESET_BOARDS: "RESET_BOARDS",
    SET_SELECTED_BOARD: "SET_SELECTED_BOARD",
    RESET_SELECTED_BOARD: "RESET_SELECTED_BOARD",
    SIGN_IN: "SIGN_IN",
    SIGN_OUT: "SIGN_OUT"
};

export default actionTags;